# Generated by Django 4.0.1 on 2022-02-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_specsheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specSheet',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
